<script setup lang="ts">
import { computed } from 'vue'
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowLeftToLine,
  ArrowRightFromLine,
  ArrowUp,
  Bot,
  BotMessageSquare,
  Check,
  Clock,
  Link2Off,
  LogOut,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleQuestionMark,
  Cloud,
  Copy,
  CornerDownLeft,
  Expand,
  FileCode,
  FileText,
  FolderOpen,
  FolderTree,
  Home,
  Loader2,
  MessageSquare,
  Minus,
  Palette,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightClose,
  PanelRightOpen,
  Pencil,
  Plus,
  Puzzle,
  RefreshCw,
  RotateCcw,
  Search,
  Send,
  Settings,
  ShieldAlert,
  Shrink,
  Smartphone,
  Sparkles,
  Square,
  Star,
  Terminal,
  Trash2,
  User,
  Wrench,
  X,
  Zap,
} from '@lucide/vue'

const props = defineProps<{
  name: string
  size?: number
  strokeWidth?: number
  fill?: boolean
}>()

const icons: Record<string, unknown> = {
  minimize: Minus,
  maximize: Square,
  restore: Copy,
  close: X,
  back: ArrowLeft,
  'arrow-left-to-line': ArrowLeftToLine,
  'arrow-right-from-line': ArrowRightFromLine,
  check: Check,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  plus: Plus,
  copy: Copy,
  trash: Trash2,
  activity: Activity,
  'alert-circle': AlertCircle,
  warning: AlertTriangle,
  user: User,
  zap: Zap,
  help: CircleQuestionMark,
  settings: Settings,
  palette: Palette,
  cloud: Cloud,
  bot: Bot,
  'bot-message-square': BotMessageSquare,
  'message-square': MessageSquare,
  send: Send,
  'file-text': FileText,
  'file-code': FileCode,
  'folder-open': FolderOpen,
  'folder-tree': FolderTree,
  loader: Loader2,
  terminal: Terminal,
  'shield-alert': ShieldAlert,
  pencil: Pencil,
  smartphone: Smartphone,
  sparkles: Sparkles,
  home: Home,
  wrench: Wrench,
  puzzle: Puzzle,
  'corner-down-left': CornerDownLeft,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  search: Search,
  square: Square,
  'link-2-off': Link2Off,
  'panel-left-close': PanelLeftClose,
  'panel-left-open': PanelLeftOpen,
  'panel-right-close': PanelRightClose,
  'panel-right-open': PanelRightOpen,
  'log-out': LogOut,
  'arrow-down': ArrowDown,
  'arrow-up': ArrowUp,
  'clock': Clock,
  expand: Expand,
  shrink: Shrink,
  star: Star,
}

const Comp = computed(() => icons[props.name] ?? null)
</script>

<template>
  <component
    :is="Comp"
    v-if="Comp"
    :size="size ?? 16"
    :stroke-width="strokeWidth ?? 2"
    :fill="fill ? 'currentColor' : 'none'"
  />
</template>
