// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearPassword() {
  return window['go']['app']['App']['ClearPassword']();
}

export function CloseSession(arg1) {
  return window['go']['app']['App']['CloseSession'](arg1);
}

export function CreateSession(arg1, arg2) {
  return window['go']['app']['App']['CreateSession'](arg1, arg2);
}

export function GetHooksConfig() {
  return window['go']['app']['App']['GetHooksConfig']();
}

export function GetSessionMessages(arg1, arg2) {
  return window['go']['app']['App']['GetSessionMessages'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function IsInitialized() {
  return window['go']['app']['App']['IsInitialized']();
}

export function ListSessions() {
  return window['go']['app']['App']['ListSessions']();
}

export function LockoutState() {
  return window['go']['app']['App']['LockoutState']();
}

export function OSUsername() {
  return window['go']['app']['App']['OSUsername']();
}

export function OpenInTerminal(arg1, arg2, arg3) {
  return window['go']['app']['App']['OpenInTerminal'](arg1, arg2, arg3);
}

export function RespondPermission(arg1, arg2, arg3) {
  return window['go']['app']['App']['RespondPermission'](arg1, arg2, arg3);
}

export function SaveHooksConfig(arg1) {
  return window['go']['app']['App']['SaveHooksConfig'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['app']['App']['SendMessage'](arg1, arg2);
}

export function SetClaudeBinary(arg1) {
  return window['go']['app']['App']['SetClaudeBinary'](arg1);
}

export function SetContext(arg1) {
  return window['go']['app']['App']['SetContext'](arg1);
}

export function SetPassword(arg1) {
  return window['go']['app']['App']['SetPassword'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['app']['App']['UpdateSettings'](arg1);
}

export function Verify(arg1) {
  return window['go']['app']['App']['Verify'](arg1);
}
