// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {providers} from '../models';
import {jsonl} from '../models';
import {settings} from '../models';
import {time} from '../models';
import {context} from '../models';

export function AdoptSession(arg1:string,arg2:string):Promise<void>;

export function AlertPermission(arg1:string,arg2:string):Promise<void>;

export function ApplyActiveProvider():Promise<void>;

export function CheckAndFixHooks():Promise<boolean>;

export function ClearPassword():Promise<void>;

export function CloseSession(arg1:string):Promise<void>;

export function CreateSession(arg1:string,arg2:string):Promise<string>;

export function EnsureHookServer():Promise<void>;

export function GetHookServerPort():Promise<number>;

export function GetHooksConfig():Promise<Record<string, any>>;

export function GetProvidersConfig():Promise<providers.Config>;

export function GetSessionMessages(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<jsonl.Message>>;

export function GetSessionStates():Promise<Record<string, string>>;

export function GetSettings():Promise<settings.Config>;

export function GetToolExecutions(arg1:string,arg2:string):Promise<Array<jsonl.ToolExecution>>;

export function HookServerURL():Promise<string>;

export function IsInitialized():Promise<boolean>;

export function ListSessions():Promise<Array<jsonl.SessionMeta>>;

export function LockoutState():Promise<number|time.Time>;

export function OSUsername():Promise<string>;

export function OpenSessionTerminal(arg1:string,arg2:string):Promise<void>;

export function PickDirectory():Promise<string>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RespondHookPermission(arg1:string,arg2:Record<string, any>):Promise<void>;

export function RespondPermission(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SaveHooksConfig(arg1:Record<string, any>):Promise<void>;

export function SaveProvidersConfig(arg1:providers.Config):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function SetClaudeBinary(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetPassword(arg1:string):Promise<void>;

export function Shutdown():Promise<void>;

export function StartTray(arg1:Array<number>):Promise<void>;

export function UpdateSettings(arg1:settings.Config):Promise<void>;

export function Verify(arg1:string):Promise<void>;

export function WriteTerminalInput(arg1:string,arg2:string):Promise<void>;
