// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {jsonl} from '../models';
import {settings} from '../models';
import {time} from '../models';
import {context} from '../models';

export function ClearPassword():Promise<void>;

export function CloseSession(arg1:string):Promise<void>;

export function CreateSession(arg1:string,arg2:string):Promise<string>;

export function GetHooksConfig():Promise<app.HooksConfig>;

export function GetSessionMessages(arg1:string,arg2:string):Promise<Array<jsonl.Message>>;

export function GetSettings():Promise<settings.Config>;

export function IsInitialized():Promise<boolean>;

export function ListSessions():Promise<Array<jsonl.SessionMeta>>;

export function LockoutState():Promise<number|time.Time>;

export function OSUsername():Promise<string>;

export function OpenInTerminal(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RespondPermission(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SaveHooksConfig(arg1:app.HooksConfig):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function SetClaudeBinary(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetPassword(arg1:string):Promise<void>;

export function UpdateSettings(arg1:settings.Config):Promise<void>;

export function Verify(arg1:string):Promise<void>;
