// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdoptSession(arg1, arg2) {
  return window['go']['app']['App']['AdoptSession'](arg1, arg2);
}

export function AlertPermission(arg1, arg2) {
  return window['go']['app']['App']['AlertPermission'](arg1, arg2);
}

export function ApplyActiveProvider() {
  return window['go']['app']['App']['ApplyActiveProvider']();
}

export function CheckAndFixHooks() {
  return window['go']['app']['App']['CheckAndFixHooks']();
}

export function ClearPassword() {
  return window['go']['app']['App']['ClearPassword']();
}

export function CloseSession(arg1) {
  return window['go']['app']['App']['CloseSession'](arg1);
}

export function CreateSession(arg1, arg2) {
  return window['go']['app']['App']['CreateSession'](arg1, arg2);
}

export function EnsureHookServer() {
  return window['go']['app']['App']['EnsureHookServer']();
}

export function GetHookServerPort() {
  return window['go']['app']['App']['GetHookServerPort']();
}

export function GetHooksConfig() {
  return window['go']['app']['App']['GetHooksConfig']();
}

export function GetProvidersConfig() {
  return window['go']['app']['App']['GetProvidersConfig']();
}

export function GetSessionMessages(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetSessionMessages'](arg1, arg2, arg3, arg4);
}

export function GetSessionStates() {
  return window['go']['app']['App']['GetSessionStates']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetToolExecutions(arg1, arg2) {
  return window['go']['app']['App']['GetToolExecutions'](arg1, arg2);
}

export function HookServerURL() {
  return window['go']['app']['App']['HookServerURL']();
}

export function IsInitialized() {
  return window['go']['app']['App']['IsInitialized']();
}

export function ListSessions() {
  return window['go']['app']['App']['ListSessions']();
}

export function LockoutState() {
  return window['go']['app']['App']['LockoutState']();
}

export function OSUsername() {
  return window['go']['app']['App']['OSUsername']();
}

export function OpenSessionTerminal(arg1, arg2) {
  return window['go']['app']['App']['OpenSessionTerminal'](arg1, arg2);
}

export function PickDirectory() {
  return window['go']['app']['App']['PickDirectory']();
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['app']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RespondHookPermission(arg1, arg2) {
  return window['go']['app']['App']['RespondHookPermission'](arg1, arg2);
}

export function RespondPermission(arg1, arg2, arg3) {
  return window['go']['app']['App']['RespondPermission'](arg1, arg2, arg3);
}

export function SaveHooksConfig(arg1) {
  return window['go']['app']['App']['SaveHooksConfig'](arg1);
}

export function SaveProvidersConfig(arg1) {
  return window['go']['app']['App']['SaveProvidersConfig'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['app']['App']['SendMessage'](arg1, arg2);
}

export function SetClaudeBinary(arg1) {
  return window['go']['app']['App']['SetClaudeBinary'](arg1);
}

export function SetContext(arg1) {
  return window['go']['app']['App']['SetContext'](arg1);
}

export function SetPassword(arg1) {
  return window['go']['app']['App']['SetPassword'](arg1);
}

export function Shutdown() {
  return window['go']['app']['App']['Shutdown']();
}

export function StartTray(arg1) {
  return window['go']['app']['App']['StartTray'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['app']['App']['UpdateSettings'](arg1);
}

export function Verify(arg1) {
  return window['go']['app']['App']['Verify'](arg1);
}

export function WriteTerminalInput(arg1, arg2) {
  return window['go']['app']['App']['WriteTerminalInput'](arg1, arg2);
}
